name: Publish Next

env:
  gha-branch: next
  gha-production: false
  gha-domain: ${{ secrets.DOMAIN_PREVIEW }}

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.gha-branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1.10.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          ALIAS_DOMAINS: ${{ env.gha-domain }}
          PRODUCTION: ${{ env.gha-production }}
