name: Update Next Docs from Packages

env:
  gha-branch: main

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs
        uses: actions/checkout@v4
        with:
          ref: ${{ env.gha-branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

  update:
    runs-on: ubuntu-latest
    needs: checkout

    strategy:
      max-parallel: 1
      matrix:
        package:
          [checkout, tools, framework, standards, api, entity-storage, logging, vault, wallet, identity, create-pr]

    steps:
      - name: Checkout ${{ matrix.package }}
        if: matrix.package == 'checkout'
        uses: actions/checkout@v4
        with:
          repository: gtscio/${{ matrix.package }}
          path: import-packages/${{ matrix.package }}
          ref: ${{ env.gha-branch }}
          token: ${{ secrets.GH_PAT }}

      - name: Copy ${{ matrix.package }} to Docs
        if: matrix.package != 'checkout' && matrix.package != 'create-pr'
        run: |
          jq -r '.packages[].name' import-packages/${{ matrix.package }}/docs/packages.json | while read pkg; do
            rm -rf docs/packages/$pkg
            cp -r import-packages/${{ matrix.package }}/packages/$pkg/docs docs/packages/$pkg
          done

          cp import-packages/${{ matrix.package }}/docs/packages.json docs/packages/${{ matrix.package }}.json
          rm -r import-packages/${{ matrix.package }}

      - name: Build
        if: matrix.package == 'create-pr'
        run: npm run build

      - name: Create Pull Request
        if: matrix.package == 'create-pr'
        run: |
          git checkout -b docs/update-${{ env.gha-branch }}-${{ github.sha }}
          git config --global user.name 'GTSC'
          git config --global user.email 'ci@gtsc.io'
          git add .
          git commit -am "Update Packages Documentation"
          git push --set-upstream origin docs/update-${{ env.gha-branch }}-${{ github.sha }}
          # Enable GitHub Actions Read and write permissions under Settings > Actions
          # Allow GitHub Actions to create and approve pull requests under Settings > Actions
          gh pr create -B ${{ env.gha-branch }} -H docs/update-${{ env.gha-branch }}-${{ github.sha }} --title 'Merge packages documentation into ${{ env.gha-branch }}' --body 'Merges the docs from the packages into ${{ env.gha-branch }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
